language: python
python:
  - "3.6"
install:
  - pip install pipenv==2018.11.26
  - pipenv install --dev --system
script:
  - black --check ./
  - mkdir .secrets
  - echo 'DemoSecret' > .secrets/secret-key
  - cd bouncer
  - python manage.py test
